language: python
python: '2.7'
before_install:
- npm install -g jshint
- npm install -g bower
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/test --all
- bin/code-analysis
after_success:
- bin/test-coverage
after_script:
- travis-artifacts upload --path parts/test
- travis-artifacts upload --target-path latest --path parts/test
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone-app-angularjs
  - secure: FGV3m/YDrm6XZSTgX5+UTKcE6xpj2/Qz096yG7WgPDaKsYphksiUQrLpvndtLJpVuRTLP1hPUjG5lVXITz6pIz3+RPLRQAJ2xfKgYm4vKd7KmHRvprsKnfD+77McS4TgexcCkPb7vvQ50EjvutdFGKqzF0uflCD1L/yXPzSVPu0=
  - secure: c0dfv+h2yXZr0QuAut3Cd2nxGQsZVlAE6GximVJmZogHUz0TC3BHo/UT5yrIVgcMmVl2QSKdZHypoZkJ+r3AUUxDIePUlHI8fKCExB8g3LXR+NXAtjSuNWRYuXVb8EqWGuEYKekdw2w5lhcZYlwP3PHONafqbF/IJw+5LpF7cS8=
